version: '3.9'
services:
  db:
    image: mysql:5.7
    restart: always
    command: mysqld --user=root --verbose
    volumes:
      # Where our data will be persisted
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    environment:
      MYSQL_DATABASE: "real_estate"
      MYSQL_USER: "estate"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "admin123"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
